# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-10 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y/%m'),
        ),
    ]
